stat_svc
ImING0/java-explore-with-me pull request #1
Opened 2023-11-18 14:03 UTC by ImING0

Реализован требуемыей функционал.

2023-11-19 08:40 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-11-19 08:40 UTC, FanaticFiz commented on stats-service/pom.xml
> +    <dependencies>
Этот модуль родительский для модулей `client, server, common`, все объявленные в нем зависимости будут и в тех модулях, что не правильно!
Например `common` содержит только dto - ему явно это все не нужно...

2023-11-19 08:40 UTC, FanaticFiz commented on stats-service/server/pom.xml
> +        <maven.compiler.source>11</maven.compiler.source>
Эти свойства достаточно указать один раз в самом верхнем `pom`

2023-11-19 08:40 UTC, FanaticFiz commented on stats-service/server/src/main/resources/schema.sql
> +drop table if exists stats cascade;
Выделяем служебные слова
`DROP TABLE IF EXISTS stats CASCADE;`

2023-11-19 08:40 UTC, FanaticFiz commented on docker-compose.yml
> +  #ewm-service:
Обязательное условие - в docker-compose иметь два сервиса, условные `stat` и `main` и  раздельные БД для каждого.

2023-11-19 08:40 UTC, FanaticFiz commented on pom.xml
> +	<modules>
Ну и тут соответственно должно быть два модуля уже на этом этапе.

2023-11-19 19:58 UTC, ImING0 commented on stats-service/pom.xml
> +    <dependencies>
На самом деле не смог выделить прям какие то зависимости, которые бы вообще не использовались в других клинетах. в поме сервера отдельно внедрены зависимости для БД, так что считаю целесообразным оставить так, как есть на текущий момент. В другом случае придется вычленять из стартеров конкретные зависимости, что не особо улучшит картинку.

2023-11-19 19:59 UTC, ImING0 commented on stats-service/server/pom.xml
> +        <maven.compiler.source>11</maven.compiler.source>
да, спасибо, убрал в главный пом

2023-11-19 19:59 UTC, ImING0 commented on stats-service/server/src/main/resources/schema.sql
> +drop table if exists stats cascade;
Сделано

2023-11-19 21:21 UTC, ImING0 commented on pom.xml
> +	<modules>
модуль добавлен

2023-11-19 21:21 UTC, ImING0 commented on docker-compose.yml
> +  #ewm-service:
добавил сервис и бд согласно шаблону

2023-11-20 19:56 UTC, FanaticFiz approved these changes

2023-11-20 19:59 UTC, merged